export enum ApiControllers {
  ROOT = '/',
  USERS = '/users',
  USER = '/user',
  AUTH = '/auth',
  SIGN_IN = '/signin',
  SIGN_UP = '/signup',
  LOGOUT = '/logout',
  REFRESH = '/refresh',
  BOOK_OFFERS = '/book-offers',
  COMMENTS = '/comments',
  SEARCH = '/search',
  PERSONAL_INFO = '/personal_info',
  EXCHANGES = '/exchanges',
  STATS = '/stats',
}
