name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'book-sharing--bsuir-api'
          heroku_email: 'kuzkovandrey@gmail.com'
        env:
          HD_DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          HD_DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          HD_DATABASE_USER_NAME: ${{secrets.DATABASE_USER_NAME}}
          HD_DATABASE_USER_PASSWORD: ${{secrets.DATABASE_USER_PASSWORD}}
          HD_DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          HD_SECRET: ${{secrets.SECRET}}
          HD_JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
          HD_JWT_ACCESS_SECRET: ${{secrets.JWT_ACCESS_SECRET}}
